server.port: 9095
#session失效时间
spring.http.encoding.force: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
server.tomcat.uri-encoding: UTF-8
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8
spring.jackson.locale: zh_CN
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false
remote.execute.token: -PzrgXeWNX7IA6tOjTCXOA==

mos:
  config:
    host: http://localhost:6001
    bucket-name: jenkins
    open-id: 12
    secret-key: "-PzrgXeWNX7IA6tOjTCXOA=="
