mos:
  config:
    host: http://192.168.0.2:6001
    bucket-name: jenkins
    open-id: 12
    secret-key: "-PzrgXeWNX7IA6tOjTCXOA=="
#tool:
#  method-name: command
#  params:
#    command: "java -version"
